### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by KaspianDev** [mineblock11/Flow#1]
Hey, normally my game sits at ~100-120fps but when I open my inventory it drops to 20fps or less.
I suspect the cause of this problem is the blur effect (it's even laggy if its set to 0%).

**Comment by mineblock11** [comment]
Could you provide logs please?

**Comment by KaspianDev** [comment]
I can send them privately but I don't see anything unusual (0 errors).

**Comment by mineblock11** [comment]
Just upload them to mclo.gs? There's nothing sensitive in log information

**Comment by KaspianDev** [comment]
I'll do that in a moment.

I've compiled the mod with code responsible for the blur effect commented. Performance issues are gone now.

**Comment by mineblock11** [comment]
> So the issue most likely is blur effect being expensive.
~~Get a better pc then ;p~~
I'll add configuration options in the next update to reduce the blur quality.

**Comment by KaspianDev** [comment]
:+1:, blur should also not render at all if it's set to zero.

**Comment by mineblock11** [comment]
Fixed in next release. 1.1.0
