### ISSUE TITLE
Compatibility with BetterRecipeMod UI

### ISSUE THREAD

**Issue by Cikodel** [mineblock11/Flow#2]
Hi, This is not a crash report issue but rather a kind of suggestion. Better Recipe Mod adds new functionalities to the recipe book interface. Therefore, when used with Flow, the new interface is not dynamic like most of the interfaces covered by the mod.
P.S. It's really a small detail, but it makes all the difference.

Well that has been my point of view.

**Comment by mineblock11** [comment]
Coming in next update.

**Comment by mineblock11** [comment]
In next update
