### ISSUE TITLE
Blur is a lot larger than before with same settings

### ISSUE THREAD

**Issue by Rafii2198** [mineblock11/Flow#4]
I updated Flow today to the latest version, and the Blur is massive. At 25% it is impossible to see anything now.
This is 10% blur on 1.1.0 version
![image](https://github.com/mineblock11/Flow/assets/26695327/fef04ba2-2b70-4810-b0d7-bbd970ffa1b9)
And 10% on 1.0.2
![image](https://github.com/mineblock11/Flow/assets/26695327/b2c4d38e-a363-4fee-bc2b-c066cb1a088f)
And this is 70% on 1.0.2, it is a lot more readable than just 10% on 1.1.0
![image](https://github.com/mineblock11/Flow/assets/26695327/eb15aaf3-8bc8-4af4-87bb-135b28cebb3d)

**Comment by mineblock11** [comment]
This is intentional, the blur shader wasn't working fully in previous versions. I see what you mean though, and could potentially decrease the blur percentage relative to the config in a future update.

**Comment by Rafii2198** [comment]
Maybe if I could suggest, make it possible to go up to 1000% or just something bigger than 100%? That way a user would have much more room to chose, as of right now I have to go to the config file and set it manually to the value I desire (0.015). I personally want to have a subtle blur that helps with focus on the gui, but is small enough to still see what is going on.

**Comment by mineblock11** [comment]
Fixed in 1.2.0 when it releases
