### ISSUE TITLE
Inventory Tabs compatibility

### ISSUE THREAD

**Issue by Steveplays28** [mineblock11/Flow#7]
[Inventory Tabs](https://modrinth.com/mod/inventory-tabs-updated)' buttons don't animate alongside the inventory currently, and the animation replays when pressing any of the buttons.
Thanks for the awesome mod though!

**Comment by mineblock11** [comment]
Will add compatibility in the next update.

**Comment by Steveplays28** [comment]
Thank you!

**Comment by mineblock11** [comment]
Inventory Tabs isn't on 1.20, I can't add compatability for it until it updates.

**Comment by Steveplays28** [comment]
Fair enough, Andrew wants to refactor Inventory Tabs in the future so this might not be such a great candidate for mod compat for now.
There's an open PR for 1.20.1 compatibility, though keep the above in mind.

Thanks for looking into it, appreciate it.
